export default {
    "avatar_url": "https://avatars3.githubusercontent.com/u/36005104?v=4",
    "bio": "I am Thong Nguyen - A Software \r\nDeveloper based in Toronto, ON who loves build things for the web",
    "blog": "thongba.io",
    "company": 'George Brown College',
    "created_at": "2018-01-31T15:49:25Z",
    "email": null,
    "events_url": "https://api.github.com/users/tylrtnguyen/events{/privacy}",
    "followers": 3,
    "followers_url": "https://api.github.com/users/tylrtnguyen/followers",
    "following": 9,
    "following_url": "https://api.github.com/users/tylrtnguyen/following{/other_user}",
    "gists_url": "https://api.github.com/users/tylrtnguyen/gists{/gist_id}",
    "gravatar_id": "",
    "hireable": null,
    "html_url": "https://github.com/tylrtnguyen",
    "id": 36005104,
    "location": "Toronto, ON",
    "login": "tylrtnguyen",
    "name": "Thong Ba Nguyen",
    "node_id": "MDQ6VXNlcjM2MDA1MTA0",
    "organizations_url": "https://api.github.com/users/tylrtnguyen/orgs",
    "public_gists": 0,
    "public_repos": 29,
    "received_events_url": "https://api.github.com/users/tylrtnguyen/received_events",
    "repos_url": "https://api.github.com/users/tylrtnguyen/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/tylrtnguyen/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tylrtnguyen/subscriptions",
    "twitter_username": null,
    "type": "User",
    "updated_at": "2020-08-04T17:11:23Z",
    "url": "https://api.github.com/users/tylrtnguyen"
}